### ISSUE TITLE
[boo] Memory access error after multiple iterations in `boo_driver` but not `iree-benchmark-module`

### ISSUE THREAD

**Issue by rkayaith** [iree-org/iree-turbine#943]
`boo_driver` crashes:
```console
$ BOO_CACHE_ON=1 BOO_CACHE_DIR=tmp-cache python boo_driver.py convbfp16 -n 16 -c 40 -H 192 -W 128 -k 40 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 3
convbfp16 -n 16 -c 40 -H 192 -W 128 -k 40 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 4 --in_layout NHWC --out_layout NHWC --fil_layout NHWC --iter 3
Memory access fault by GPU node-2 (Agent handle: 0x1be9c110) on address 0x74cc40c00000. Reason: Unknown.
Aborted (core dumped)
```
`iree-benchmark-module` runs:
```console
$ iree-benchmark-module --module=tmp-cache/conv_2d_bfloat16_weight_backward_16x192x128x40_nhwc_40x3x3x40_fhwc_nhwf_2x2s_1x1p_1x1d_1g/282fd48339cbd5e63ed86446f84a2203d9dcfb80.vmfb --input=16x96x64x40xbf16=1 --input=16x192x128x40xbf16=1 --output='' --device=hip  --function=conv_2d_bfloat16_weight_backward_16x192x128x40_nhwc_40x3x3x40_fhwc_nhwf_2x2s_1x1p_1x1d_1g
2025-06-16T14:23:25-07:00
Running /home/rkayaith/repos/iree/build/runtime/build/i/d/python_packages/iree_runtime/iree/_runtime_libs/iree-benchmark-module
Run on (96 X 3810.79 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x96)
  L1 Instruction 32 KiB (x96)
  L2 Unified 1024 KiB (x96)
  L3 Unified 32768 KiB (x16)
Load Average: 49.98, 16.27, 9.91
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                                    Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_conv_2d_bfloat16_weight_backward_16x192x128x40_nhwc_40x3x3x40_fhwc_nhwf_2x2s_1x1p_1x1d_1g/process_time/real_time       1.15 ms         1.11 ms          629 items_per_second=866.779/s
```

This seems to always fail on the 3rd iteration (e.g. passing `--iter 2` to `boo_driver` will succeed)

IREE commit:  https://github.com/iree-org/iree/commit/cbbdeee906fe18289884d9efd70556d5f51c47cd
turbine commit: 89d4060ffb7e1a432373bd47e6af8ee8452c2d85

**Comment by rkayaith** [comment]
This _could_ be a kernel (i.e. upstream IREE) issue, but in that case we should figure out how to repro outside of `boo`.

**Comment by martin-luecke** [comment]
I am not sure if this is connected, but this week I see a similar error just running `pytest .` in the turbine repo:
```
tests/kernel/boo/ops/boo_conv_test.py::testBackwardCacheBoo[True-False] Memory access fault by GPU node-2 (Agent handle: 0x2f4ec710) on address 0x7ee616900000. Reason: Unknown.
Fatal Python error: Aborted

Thread 0x00007f2942b3e000 (most recent call first):
  File "iree-turbine/.venv/lib/python3.11/site-packages/torch/fx/proxy.py"Fatal Python error: Segmentation fault
```
The segfault prevents running any subsequent tests

**Comment by zjgarvey** [comment]
@martin-luecke on top of main? Which iree version?

The CI is green, so I'm not sure why this would be different for you locally. I'll take a closer look today.

**Comment by AWoloszyn** [comment]
The issue appears to be here:
```
   0x00007ffeab0cdc94 <+1172>:  s_mov_b32 s58, s32
   0x00007ffeab0cdc98 <+1176>:  v_cndmask_b32_e64 v2, 0, v20, s[20:21]
   0x00007ffeab0cdca0 <+1184>:  scratch_store_short off, v2, s58 offset:14
=> 0x00007ffeab0cdca8 <+1192>:  scratch_load_dwordx4 v[2:5], off, s58
   0x00007ffeab0cdcb0 <+1200>:  s_mov_b64 s[26:27], exec
   0x00007ffeab0cdcb4 <+1204>:  s_mov_b64 s[34:35], exec
   0x00007ffeab0cdcb8 <+1208>:  s_mov_b64 s[36:37], exec
```

**Comment by AWoloszyn** [comment]
One thing to note is that your rocm version packaged with pytorch may not match your rocm version on the system you are running, this may cause the difference you are seeing.

**Comment by rkayaith** [comment]
My torch rocm version was slightly behind my system one (6.2 vs 6.4), but I tried out [the rock](https://github.com/ROCm/TheRock/blob/main/RELEASES.md#installing-pytorch-python-packages) to get a matching pytorch rocm + system rocm, but I'm still seeing the same issue.

**Comment by rkayaith** [comment]
Looking at the asm a bit more, here's the LLVM IR related to scratch/private memory:
```ll
  ...
  %79 = alloca [8 x bfloat], align 2, addrspace(5)
  ...
  %82 = getelementptr inbounds nuw i8, ptr addrspace(5) %79, i32 14
  store <1 x bfloat> %81, ptr addrspace(5) %82, align 2
  %83 = load <8 x bfloat>, ptr addrspace(5) %79, align 2
  ...
  %86 = alloca [8 x bfloat], align 2, addrspace(5)
  br i1 %44, label %87, label %90

87:                                               ; preds = %74
  %88 = getelementptr inbounds nuw i8, ptr addrspace(5) %86, i32 14
  ...
  store <1 x bfloat> %89, ptr addrspace(5) %88, align 2
  %unmaskedload.pre = load <8 x bfloat>, ptr addrspace(5) %86, align 2
  br label %90
  ...
```
There's only two `alloca`'s in the private address space, both of size `8xbfloat = 16B`.

In the final assembly we end up with:
```
.LBB0_0:
    ...
    s_mov_b32 s32, 16
    ...
    s_mov_b32 s31, s32
    ...
    scratch_store_short off, v2, s31 offset:14
    scratch_load_dwordx4 v[2:5], off, s31        // offset = 16
    s_add_i32 s32, s31, 0x400
    ...
    s_mov_b32 s58, s32
    scratch_store_short off, v2, s58 offset:14
=>  scratch_load_dwordx4 v[2:5], off, s58        // offset = 16 + 0x400 = 1040
    ...
```
I don't understand where the `0x400` offset comes from here, shouldn't that be equal to the `alloca` size, i.e. `16`?

The full assembly is here: https://gist.github.com/rkayaith/a91d8e2a01651c6f027ab5fc190e14e3

**Comment by rkayaith** [comment]
The codegen issue is resolved by https://github.com/iree-org/iree/pull/21166

**Comment by rkayaith** [comment]
closing as the fix has been merged
